import 'fake-indexeddb/auto';
import { beforeEach, describe, expect, it } from 'vitest';
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { AppProviders } from '@/app/providers';
import { db } from '@/data/db';
import { ensureSeeded, resetLocalStore } from '@/data/repositories';
import { PromptsPage } from './PromptsPage';

const MOST_USED = 'Meeting debrief';
const UNUSED = 'Copy critique against the doctrine';

function renderPage(entry = '/prompts') {
  return render(
    <MemoryRouter initialEntries={[entry]}>
      <AppProviders>
        <PromptsPage />
      </AppProviders>
    </MemoryRouter>,
  );
}

function rowFor(title: string): HTMLElement {
  const row = screen.getByText(title).closest('li');
  if (!row) throw new Error(`No prompt row for ${title}`);
  return row;
}

beforeEach(async () => {
  await resetLocalStore(db);
  await ensureSeeded(db, new Date());
});

describe('PromptsPage', () => {
  it('is browsable with no provider configured at all', async () => {
    renderPage();

    expect(await screen.findByText(MOST_USED)).toBeDefined();
    expect(screen.getByText(UNUSED)).toBeDefined();
    expect(screen.queryByText(/Generated by/)).toBeNull();
  });

  it('ranks by use count, which counts starts and not results', async () => {
    renderPage();
    await screen.findByText(MOST_USED);

    const titles = screen.getAllByRole('listitem').map((row) => row.textContent ?? '');
    expect(titles[0]).toContain(MOST_USED);
    expect(within(rowFor(MOST_USED)).getByText(/used 11/)).toBeDefined();
  });

  it('shows the placeholders a prompt expects when it is opened', async () => {
    renderPage();
    await screen.findByText(MOST_USED);

    fireEvent.click(screen.getByRole('button', { name: 'Renewal framing memo' }));

    await waitFor(() => {
      expect(within(rowFor('Renewal framing memo')).getAllByText('{{client}}').length).toBeGreaterThan(
        0,
      );
    });
  });

  it('marks a gated prompt, because its output passes a human gate', async () => {
    renderPage();
    await screen.findByText(UNUSED);

    expect(within(rowFor(UNUSED)).getByText('Gated')).toBeDefined();
  });

  it('filters by intent from the query string', async () => {
    renderPage('/prompts?intent=critique');

    expect(await screen.findByText(UNUSED)).toBeDefined();
    expect(screen.queryByText(MOST_USED)).toBeNull();
  });

  it('reads the variables off a saved body rather than asking for them twice', async () => {
    renderPage();
    await screen.findByText(MOST_USED);

    fireEvent.change(screen.getByLabelText('Save a prompt'), {
      target: { value: 'Discovery recap' },
    });
    fireEvent.change(screen.getByLabelText('Prompt body'), {
      target: { value: 'Recap the call with {{prospect}}.' },
    });
    fireEvent.click(screen.getByRole('button', { name: 'Save prompt' }));

    expect(await screen.findByText(/1 variables read off the body/)).toBeDefined();
  });
});
