import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { agentKernel, type ProviderHealth } from '@/agents';
import { useSovereign } from '@/app/context';
import { runAgentTurn, startAgentSession } from '@/data/mutations';
import type { AgentMessage, AgentSession } from '@/domain';
import { relativeTime } from '@/lib/clock';
import { cn } from '@/lib/cn';
import { DemoBadge, EmptyLine, Panel, SectionLabel, StatePill } from '@/ui/primitives';
import {
  anyProviderReady,
  providerStateLabel,
  providerStateTone,
  providerStatusRows,
  providerSummary,
  selectSessions,
  sessionThread,
  workspaceCounts,
} from './workspace';

const actionButton = 'label-caps border px-2.5 py-1 transition-colors disabled:opacity-40';

/**
 * Roster health, read through the kernel. The surface never imports an adapter,
 * so what it prints is exactly what the kernel would act on.
 */
function useProviderHealth(): { health: ProviderHealth[]; probing: boolean } {
  const [health, setHealth] = useState<ProviderHealth[]>([]);
  const [probing, setProbing] = useState(true);

  useEffect(() => {
    let live = true;
    void agentKernel
      .health()
      .then((rows) => {
        if (live) setHealth(rows);
      })
      .catch(() => {
        if (live) setHealth([]);
      })
      .finally(() => {
        if (live) setProbing(false);
      });
    return () => {
      live = false;
    };
  }, []);

  return { health, probing };
}

function MessageRow({ message, now }: { message: AgentMessage; now: Date }) {
  const refused = message.outcome === 'refused';

  return (
    <li className="border-b border-line/60 py-2.5 last:border-b-0">
      <p className="flex flex-wrap items-center gap-2">
        <span className="label-caps text-faint">{message.role}</span>
        {message.generated ? (
          <StatePill tone="sentinel" title={`Generated by ${message.provider ?? 'a provider'}.`}>
            Generated by {message.provider ?? 'provider'}
          </StatePill>
        ) : refused ? (
          <StatePill tone="gold" title="The kernel declined to run this turn.">
            Refused · {message.reason ?? 'no reason recorded'}
          </StatePill>
        ) : null}
        {message.source === 'demo' ? <DemoBadge /> : null}
        <span className="font-mono text-[0.65rem] text-faint">{relativeTime(message.at, now)}</span>
      </p>
      <p
        className={cn(
          'mt-1 text-sm leading-6 whitespace-pre-wrap',
          refused ? 'text-gold/90' : message.role === 'user' ? 'text-ivory' : 'text-muted',
        )}
      >
        {message.content}
      </p>
    </li>
  );
}

function Composer({
  session,
  ready,
  onSent,
}: {
  session: AgentSession;
  ready: boolean;
  onSent: (message: string) => void;
}) {
  const [text, setText] = useState('');
  const [busy, setBusy] = useState(false);

  return (
    <form
      className="mt-3 border-t border-line pt-3"
      onSubmit={(event) => {
        event.preventDefault();
        if (text.trim().length === 0) return;
        setBusy(true);
        void runAgentTurn(session.id, text, agentKernel)
          .then((result) => {
            setText('');
            onSent(
              result.ok
                ? 'The provider answered. Output still passes the human gate before it reaches anyone.'
                : (result.reason ??
                    'The kernel refused the turn. The refusal is written into the thread.'),
            );
          })
          .catch((cause: unknown) => {
            onSent(cause instanceof Error ? cause.message : 'The turn failed.');
          })
          .finally(() => {
            setBusy(false);
          });
      }}
    >
      <label className="label-caps text-faint" htmlFor="agent-turn">
        Send a turn
      </label>
      <textarea
        id="agent-turn"
        value={text}
        onChange={(event) => {
          setText(event.target.value);
        }}
        rows={3}
        placeholder={
          ready
            ? 'Your message to the configured provider'
            : 'No adapter can run a turn. Sending records the message and the kernel’s refusal.'
        }
        className="mt-1 w-full border border-line bg-surface/60 px-2 py-1.5 text-sm leading-6 text-on-surface outline-none placeholder:text-faint focus:border-gold/50"
      />
      <div className="mt-2 flex flex-wrap items-center gap-2">
        <button
          type="submit"
          disabled={busy || text.trim().length === 0}
          className={cn(
            actionButton,
            'border-gold/50 text-gold hover:border-gold hover:text-ivory',
          )}
        >
          {ready ? 'Send through the kernel' : 'Send and record the refusal'}
        </button>
        {session.requiresApproval ? (
          <span className="text-xs text-faint">
            Anything this session produces requires a human gate before it is used.
          </span>
        ) : null}
      </div>
    </form>
  );
}

function ProviderRoster({ health, probing }: { health: ProviderHealth[]; probing: boolean }) {
  const { dataset } = useSovereign();
  const rows = useMemo(
    () => providerStatusRows(health, dataset.integrations),
    [health, dataset.integrations],
  );

  return (
    <Panel title="Provider adapters">
      {probing ? (
        <EmptyLine>Asking each adapter what it can do…</EmptyLine>
      ) : rows.length === 0 ? (
        <EmptyLine>No adapter is registered with the kernel.</EmptyLine>
      ) : (
        <ul className="space-y-2">
          {rows.map(({ health: entry, integration }) => (
            <li key={entry.id} className="border-b border-line/60 pb-2 last:border-b-0 last:pb-0">
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-sm text-ivory">{entry.label}</span>
                <StatePill tone={providerStateTone(entry.state)}>
                  {providerStateLabel[entry.state]}
                </StatePill>
                {entry.external ? (
                  <StatePill tone="muted" title="Completing would leave the browser.">
                    External
                  </StatePill>
                ) : null}
              </div>
              <p className="mt-0.5 text-xs leading-5 text-muted">{entry.detail}</p>
              {integration ? (
                <p className="mt-0.5 font-mono text-[0.65rem] text-faint">
                  registry:{' '}
                  <Link to="/integrations" className="hover:text-ivory">
                    {integration.name}
                  </Link>
                </p>
              ) : null}
            </li>
          ))}
        </ul>
      )}
    </Panel>
  );
}

export function AiWorkspacePage() {
  const { dataset, ready: storeReady } = useSovereign();
  const { health, probing } = useProviderHealth();
  const [selected, setSelected] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const now = useMemo(() => new Date(), []);

  const sessions = useMemo(() => selectSessions(dataset), [dataset]);
  const counts = useMemo(() => workspaceCounts(dataset), [dataset]);
  const active = sessions.find((session) => session.id === selected) ?? sessions[0];
  const thread = useMemo(
    () => (active ? sessionThread(dataset, active) : null),
    [dataset, active],
  );
  const providerReady = anyProviderReady(health);

  function newSession() {
    setBusy(true);
    setMessage(null);
    void startAgentSession({ title: 'Untitled session', intent: 'workspace' })
      .then((session) => {
        if (session) setSelected(session.id);
      })
      .catch((cause: unknown) => {
        setMessage(cause instanceof Error ? cause.message : 'Opening the session failed.');
      })
      .finally(() => {
        setBusy(false);
      });
  }

  return (
    <div className="mx-auto max-w-6xl px-6 py-6">
      <header className="mb-5">
        <SectionLabel>Cognition</SectionLabel>
        <h1 className="mt-1 font-display text-2xl text-ivory">AI Workspace</h1>
        <p className="mt-1 max-w-3xl text-sm text-muted">
          Every turn goes through the Agent Kernel, which selects an adapter, applies the policy, and
          refuses when nothing can run. A refusal is written into the thread exactly as a completion
          would be, so nothing here can be mistaken for output a model never produced.
        </p>

        <p
          className={cn(
            'mt-3 border-y border-line py-2.5 text-sm',
            providerReady ? 'text-sentinel' : 'text-gold',
          )}
        >
          {probing ? 'Asking each adapter what it can do…' : providerSummary(health)}
        </p>

        <dl className="mt-3 flex flex-wrap items-baseline gap-x-8 gap-y-2">
          <div>
            <dt className="label-caps text-faint">Sessions</dt>
            <dd className="font-mono text-lg text-ivory tabular-nums">{counts.sessions}</dd>
          </div>
          <div>
            <dt className="label-caps text-faint">Turns sent</dt>
            <dd className="font-mono text-lg text-muted tabular-nums">{counts.turns}</dd>
          </div>
          <div>
            <dt className="label-caps text-faint">Generated</dt>
            <dd className="font-mono text-lg text-sentinel tabular-nums">{counts.generated}</dd>
          </div>
          <div>
            <dt className="label-caps text-faint">Refused</dt>
            <dd className="font-mono text-lg text-gold tabular-nums">{counts.refused}</dd>
          </div>
        </dl>
      </header>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]">
        <div className="space-y-4">
          <Panel
            title="Sessions"
            action={
              <button
                type="button"
                disabled={busy}
                onClick={newSession}
                className={cn(
                  'label-caps border px-2 py-0.5 transition-colors disabled:opacity-40',
                  'border-line text-muted hover:border-gold/40 hover:text-ivory',
                )}
              >
                New
              </button>
            }
          >
            {!storeReady ? (
              <EmptyLine>Opening the local store…</EmptyLine>
            ) : sessions.length === 0 ? (
              <EmptyLine>No session has been opened yet.</EmptyLine>
            ) : (
              <ul className="space-y-1">
                {sessions.map((session) => (
                  <li key={session.id}>
                    <button
                      type="button"
                      onClick={() => {
                        setSelected(session.id);
                        setMessage(null);
                      }}
                      aria-current={active?.id === session.id}
                      className={cn(
                        'w-full border px-2 py-1.5 text-left transition-colors',
                        active?.id === session.id
                          ? 'border-gold/50 bg-gold-faint'
                          : 'border-transparent hover:border-line',
                      )}
                    >
                      <span className="flex flex-wrap items-center gap-2">
                        <span className="text-sm text-ivory">{session.title}</span>
                        {session.source === 'demo' ? <DemoBadge /> : null}
                        {session.unansweredCount > 0 ? (
                          <StatePill tone="gold">{session.unansweredCount} unanswered</StatePill>
                        ) : null}
                      </span>
                      <span className="mt-0.5 block font-mono text-[0.65rem] text-faint">
                        {session.intent} · {relativeTime(session.lastActivityAt, now)}
                      </span>
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </Panel>

          <ProviderRoster health={health} probing={probing} />
        </div>

        <Panel title={active ? active.title : 'No session selected'}>
          {!thread || !active ? (
            <EmptyLine>Open a session to send a turn through the kernel.</EmptyLine>
          ) : (
            <>
              <p className="mb-2 flex flex-wrap items-baseline gap-x-3 font-mono text-[0.65rem] text-faint">
                <span>intent {active.intent}</span>
                <span aria-hidden>·</span>
                <span>{thread.turns} turns</span>
                <span aria-hidden>·</span>
                <span>{thread.generated} generated</span>
                <span aria-hidden>·</span>
                <span className={thread.refused > 0 ? 'text-gold' : undefined}>
                  {thread.refused} refused
                </span>
                {thread.prompt ? (
                  <>
                    <span aria-hidden>·</span>
                    <Link to="/prompts" className="hover:text-ivory">
                      {thread.prompt.title}
                    </Link>
                  </>
                ) : null}
              </p>

              {thread.messages.length === 0 ? (
                <EmptyLine>Nothing has been said in this session.</EmptyLine>
              ) : (
                <ul>
                  {thread.messages.map((entry) => (
                    <MessageRow key={entry.id} message={entry} now={now} />
                  ))}
                </ul>
              )}

              <Composer session={active} ready={providerReady} onSent={setMessage} />
              {message ? <p className="mt-2 text-xs text-muted">{message}</p> : null}
            </>
          )}
        </Panel>
      </div>
    </div>
  );
}
