import 'fake-indexeddb/auto';
import { beforeEach, describe, expect, it } from 'vitest';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { AppProviders } from '@/app/providers';
import { db } from '@/data/db';
import { ensureSeeded, resetLocalStore } from '@/data/repositories';
import { AiWorkspacePage } from './AiWorkspacePage';

function renderPage() {
  return render(
    <MemoryRouter initialEntries={['/ai']}>
      <AppProviders>
        <AiWorkspacePage />
      </AppProviders>
    </MemoryRouter>,
  );
}

beforeEach(async () => {
  await resetLocalStore(db);
  await ensureSeeded(db, new Date());
});

describe('AiWorkspacePage', () => {
  it('says no adapter can run rather than implying one is connected', async () => {
    renderPage();

    expect(await screen.findByText(/No adapter can run a turn/i)).toBeDefined();
    expect(screen.queryByText(/adapters can run a turn:/i)).toBeNull();
  });

  it('prints the roster the kernel reports, with each adapter in its honest state', async () => {
    renderPage();

    expect(await screen.findByText('Local model')).toBeDefined();
    expect(screen.getByText('Anthropic Claude')).toBeDefined();
    expect(screen.getAllByText('Awaiting credentials').length).toBeGreaterThan(0);
    expect(screen.getByText('Not configured')).toBeDefined();
    expect(screen.queryByText('Ready')).toBeNull();
  });

  it('names the variable that would configure the local adapter', async () => {
    renderPage();

    expect(await screen.findByText(/VITE_LOCAL_AI_URL/)).toBeDefined();
  });

  it('shows the seeded refusals as refusals, never as generated output', async () => {
    renderPage();

    expect((await screen.findAllByText(/Renewal memo for TruOak/))[0]).toBeDefined();
    expect(screen.getAllByText(/Refused ·/).length).toBeGreaterThan(0);
    expect(screen.queryByText(/Generated by/)).toBeNull();
  });

  it('counts the turns the kernel could not run', async () => {
    renderPage();
    await screen.findAllByText(/Renewal memo for TruOak/);

    const refused = screen.getByText('Refused').closest('div');
    expect(refused?.textContent).toContain('2');
  });

  it('writes the kernel refusal into the thread when a turn is sent', async () => {
    renderPage();
    await screen.findAllByText(/Renewal memo for TruOak/);

    fireEvent.change(screen.getByLabelText('Send a turn'), {
      target: { value: 'Draft the memo.' },
    });
    fireEvent.click(screen.getByRole('button', { name: /Send and record the refusal/i }));

    expect(await screen.findByText('Draft the memo.')).toBeDefined();
    await waitFor(() => {
      expect(screen.getAllByText(/Refused ·/).length).toBeGreaterThan(1);
    });
    expect(screen.queryByText(/Generated by/)).toBeNull();
  });

  it('states the human gate rather than leaving the policy implicit', async () => {
    renderPage();

    expect(
      await screen.findByText(/requires a human gate before it is used/i),
    ).toBeDefined();
  });
});
