import type { IntegrationCategory, IntegrationState } from '@/domain';

export interface IntegrationCatalogEntry {
  id: string;
  name: string;
  category: IntegrationCategory;
  /**
   * Baseline state from docs/reports/INTEGRATION_REPORT.md. Nothing is `connected`
   * in Wave 1: no health probe exists yet, so claiming green would be a lie.
   */
  state: IntegrationState;
  capabilities: string[];
  rationale: string;
  /** Substrate members are the systems the Command Center depends on to operate. */
  substrate?: boolean;
}

export const integrationCatalog: readonly IntegrationCatalogEntry[] = [
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'productivity',
    state: 'awaiting_credentials',
    capabilities: ['Meeting webhooks', 'Booking sync'],
    rationale: 'Env-gated in ContentDone. No probe from the Command Surface yet.',
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'automation',
    state: 'awaiting_credentials',
    capabilities: ['Workflow triggers', 'Publish fan-out'],
    rationale: 'Cloud instance exists in deploy docs; credentials never reach a Pages bundle.',
    substrate: true,
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'data',
    state: 'awaiting_credentials',
    capabilities: ['Lead tables', 'Content calendar mirror'],
    rationale: 'Env-gated in ContentDone.',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'publishing',
    state: 'awaiting_credentials',
    capabilities: ['Post publishing via n8n'],
    rationale: 'Routed through n8n; unverified.',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    category: 'publishing',
    state: 'awaiting_credentials',
    capabilities: ['Page publishing via n8n'],
    rationale: 'Routed through n8n; unverified.',
  },
  {
    id: 'crm-webhook',
    name: 'CRM Webhook',
    category: 'crm',
    state: 'awaiting_credentials',
    capabilities: ['Lead push', 'Stage sync'],
    rationale: 'Env-gated in ContentDone.',
  },
  {
    id: 'local-ai',
    name: 'Local AI (Ollama)',
    category: 'ai',
    state: 'awaiting_credentials',
    capabilities: ['Local completions'],
    rationale: 'Implemented in ContentDone; no endpoint health check from this surface.',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'ai',
    state: 'awaiting_credentials',
    capabilities: ['Completions', 'Embeddings'],
    rationale: 'Provider stub only. All calls must pass the Agent Kernel.',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    category: 'ai',
    state: 'awaiting_credentials',
    capabilities: ['Completions'],
    rationale: 'Provider stub only. All calls must pass the Agent Kernel.',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    category: 'ai',
    state: 'awaiting_credentials',
    capabilities: ['Completions'],
    rationale: 'Not implemented anywhere in the ecosystem yet.',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'ai',
    state: 'awaiting_credentials',
    capabilities: ['Provider routing'],
    rationale: 'Not implemented anywhere in the ecosystem yet.',
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    category: 'productivity',
    state: 'awaiting_credentials',
    capabilities: ['Gmail', 'Calendar', 'Drive'],
    rationale: 'One connector family with discrete capability flags. Needs OAuth on an API.',
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'productivity',
    state: 'awaiting_credentials',
    capabilities: ['Docs', 'Databases'],
    rationale: 'No implementation yet.',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    category: 'productivity',
    state: 'disabled',
    capabilities: ['Tasks'],
    rationale: 'Disabled until workflow demand is proven. Tasks live locally in Wave 1.',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'data',
    state: 'awaiting_credentials',
    capabilities: ['Read-only repo signals'],
    rationale: 'Read-only first when credentials arrive.',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'data',
    state: 'disabled',
    capabilities: ['Postgres', 'Auth'],
    rationale: 'Disabled until the remote store is chosen (Wave 7 decision).',
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    category: 'communication',
    state: 'awaiting_credentials',
    capabilities: ['Transactional email'],
    rationale: 'No implementation yet.',
  },
  {
    id: 'apollo',
    name: 'Apollo',
    category: 'crm',
    state: 'disabled',
    capabilities: ['Lead enrichment'],
    rationale: 'Disabled until the lead-enrichment wave.',
  },
  {
    id: 'zoominfo',
    name: 'ZoomInfo',
    category: 'crm',
    state: 'disabled',
    capabilities: ['Lead enrichment'],
    rationale: 'Disabled. Redundant with Apollo until proven otherwise.',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'crm',
    state: 'disabled',
    capabilities: ['CRM sync'],
    rationale: 'Disabled. Airtable and the CRM webhook come first.',
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    state: 'awaiting_credentials',
    capabilities: ['Alerts', 'Approvals relay'],
    rationale: 'No implementation yet.',
  },
  {
    id: 'hermes-memory',
    name: 'Hermes Memory',
    category: 'mcp',
    state: 'awaiting_credentials',
    capabilities: ['Long-term memory'],
    rationale: 'Target MCP server. Not built.',
    substrate: true,
  },
  {
    id: 'hermesbrain',
    name: 'HermesBrain',
    category: 'mcp',
    state: 'awaiting_credentials',
    capabilities: ['Reasoning orchestration'],
    rationale: 'Brand surface only today. No runtime.',
    substrate: true,
  },
  {
    id: 'sovereign-mind-mcp',
    name: 'Sovereign Mind MCP',
    category: 'mcp',
    state: 'awaiting_credentials',
    capabilities: ['Internal tools'],
    rationale: 'Target MCP gateway. Not built.',
    substrate: true,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'productivity',
    state: 'disabled',
    capabilities: ['Authoring'],
    rationale: 'Development tool, not an in-product integration.',
  },
  {
    id: 'contentdone',
    name: 'ContentDone API',
    category: 'automation',
    state: 'awaiting_credentials',
    capabilities: ['Content engine', 'Lead engine', 'Health probe'],
    rationale: 'Execution substrate. Wave 7 adapter; no base URL configured yet.',
    substrate: true,
  },
  {
    id: 'leadscheduler',
    name: 'LeadScheduler Pro',
    category: 'crm',
    state: 'disabled',
    capabilities: ['Pipeline doctrine', 'CSV exports'],
    rationale: 'Static collateral with no live API. Domain source only.',
    substrate: true,
  },
] as const;
