import { INTEGRATION_STATES } from '@/integrations/state';
import { APPROVAL_FILTERS } from '@/modules/approvals/queue';
import { CRM_TEMPERATURES, CRM_VIEWS } from '@/modules/crm/crm';
import { CALENDAR_WEEKS } from '@/modules/calendar/calendar';
import { INBOX_SEVERITY_FILTERS, INBOX_STATUS_FILTERS } from '@/modules/inbox/notifications';
import { MEETING_WINDOWS } from '@/modules/meetings/meetings';
import { PIPELINE_STAGE_FILTERS } from '@/modules/pipeline/pipeline';
import { PROJECT_FILTERS } from '@/modules/projects/projects';
import { TASK_PRIORITY_FILTERS, TASK_STATUS_FILTERS } from '@/modules/tasks/tasks';
import { enabledModules, enabledRecordRoutes } from './modules';

/**
 * The only query parameters an enabled route is allowed to carry, and the
 * only values each one may take. Anything else on an otherwise-enabled path
 * is treated as unsafe rather than silently passed through.
 */
const ALLOWED_QUERY_PARAMS: Record<string, Record<string, readonly string[]>> = {
  '/inbox': {
    status: INBOX_STATUS_FILTERS,
    severity: INBOX_SEVERITY_FILTERS,
  },
  '/approvals': {
    status: APPROVAL_FILTERS,
  },
  '/integrations': {
    state: [...INTEGRATION_STATES, 'all'],
  },
  '/crm': {
    view: CRM_VIEWS,
    temperature: CRM_TEMPERATURES,
  },
  '/pipeline': {
    stage: PIPELINE_STAGE_FILTERS,
  },
  '/tasks': {
    status: TASK_STATUS_FILTERS,
    priority: TASK_PRIORITY_FILTERS,
  },
  '/projects': {
    status: PROJECT_FILTERS,
  },
  '/calendar': {
    week: CALENDAR_WEEKS,
  },
  '/meetings': {
    when: MEETING_WINDOWS,
  },
};

/**
 * Record ids are generated by the seeder or by `createTask`, so they are lower
 * alphanumerics and hyphens. Anything else in a detail segment is refused rather
 * than URL-decoded and hoped over.
 */
const RECORD_ID = /^[a-z0-9][a-z0-9-]*$/;

function enabledPaths(): Set<string> {
  return new Set(enabledModules().map((module) => module.path));
}

/** True when `pathname` is an enabled record detail route with a legal id. */
function matchesRecordRoute(pathname: string): boolean {
  return enabledRecordRoutes().some((route) => {
    const prefix = route.pattern.replace(/:id$/, '');
    if (!pathname.startsWith(prefix)) return false;
    const id = pathname.slice(prefix.length);
    return RECORD_ID.test(id);
  });
}

/**
 * True when `href` is exactly an enabled internal route — a module path or one
 * of that module's declared record detail routes — optionally followed by a
 * known-safe query string for that route (ARCHITECTURE_AUDIT §5.3;
 * `docs/reviews/WAVE_2_GPT_REVIEW.md` M1). Everything else — external URLs,
 * protocol-relative URLs, `javascript:`/`data:`/other schemes, malformed
 * strings, and planned-module paths — is unsafe.
 */
export function isSafeInternalHref(href: string): boolean {
  if (typeof href !== 'string') return false;
  const trimmed = href.trim();
  if (trimmed.length === 0) return false;

  // A single leading slash only. Rejects protocol-relative ("//host"),
  // backslash tricks some browsers normalize to "//" ("/\host"), and every
  // absolute URL ("https:", "javascript:", "mailto:", ...).
  if (!trimmed.startsWith('/') || trimmed.startsWith('//') || trimmed.startsWith('/\\')) {
    return false;
  }

  let parsed: URL;
  try {
    parsed = new URL(trimmed, 'https://internal.invalid');
  } catch {
    return false;
  }

  // The base origin must survive parsing untouched; a route that manages to
  // smuggle a different host or scheme through is not internal.
  if (parsed.origin !== 'https://internal.invalid') return false;

  const isModulePath = enabledPaths().has(parsed.pathname);
  if (!isModulePath && !matchesRecordRoute(parsed.pathname)) return false;

  // Detail routes take no query string: their whole state is the record id.
  if (!isModulePath && parsed.search.length > 0) return false;

  const allowedParams = ALLOWED_QUERY_PARAMS[parsed.pathname];
  for (const [key, value] of parsed.searchParams) {
    const allowedValues = allowedParams?.[key];
    if (!allowedValues || !allowedValues.includes(value)) return false;
  }

  return true;
}

/**
 * Returns `href` unchanged when it is a safe enabled internal route, and
 * `fallback` otherwise. Every notification/record href must pass through
 * this before it reaches a `Link`/`navigate` call.
 */
export function normalizeInternalHref(href: string | undefined | null, fallback: string): string {
  if (href === undefined || href === null) return fallback;
  return isSafeInternalHref(href) ? href : fallback;
}

function recordHref(routeId: string, id: string, fallback: string): string {
  const route = enabledRecordRoutes().find((entry) => entry.id === routeId);
  if (!route) return fallback;
  return normalizeInternalHref(route.pattern.replace(':id', id), fallback);
}

/**
 * The only sanctioned builders for record links. Each one validates its own
 * output, so an id the router or the allowlist would refuse degrades to the
 * module list instead of a dead or unsafe link.
 */
export function personHref(id: string): string {
  return recordHref('crm-person', id, '/crm');
}

export function companyHref(id: string): string {
  return recordHref('crm-company', id, '/crm?view=companies');
}

export function opportunityHref(id: string): string {
  return recordHref('pipeline-opportunity', id, '/pipeline');
}
